"""add_financial_years_archive_and_backup_tables

Revision ID: 5a07ac224708
Revises: c7a1801d7807
Create Date: 2026-02-23 20:01:22.312774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a07ac224708'
down_revision: Union[str, None] = 'c7a1801d7807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_records_created_at'), 'backup_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_backup_records_id'), 'backup_records', ['id'], unique=False)
    op.create_index(op.f('ix_backup_records_user_id'), 'backup_records', ['user_id'], unique=False)
    op.create_table('financial_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('year_start', sa.Date(), nullable=False),
    sa.Column('year_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_years_client_id'), 'financial_years', ['client_id'], unique=False)
    op.create_index(op.f('ix_financial_years_id'), 'financial_years', ['id'], unique=False)
    op.create_table('archived_invoice_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('original_invoice_id', sa.Integer(), nullable=False),
    sa.Column('original_transaction_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('suggested_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_invoice_matches_financial_year_id'), 'archived_invoice_matches', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_archived_invoice_matches_id'), 'archived_invoice_matches', ['id'], unique=False)
    op.create_table('archived_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('file_reference', sa.String(), nullable=True),
    sa.Column('original_created_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_invoices_client_id'), 'archived_invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_archived_invoices_financial_year_id'), 'archived_invoices', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_archived_invoices_id'), 'archived_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_archived_invoices_session_id'), 'archived_invoices', ['session_id'], unique=False)
    op.create_table('archived_overall_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('system_opening_balance', sa.Float(), nullable=True),
    sa.Column('bank_closing_balance', sa.Float(), nullable=True),
    sa.Column('original_created_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_overall_reconciliations_client_id'), 'archived_overall_reconciliations', ['client_id'], unique=False)
    op.create_index(op.f('ix_archived_overall_reconciliations_financial_year_id'), 'archived_overall_reconciliations', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_archived_overall_reconciliations_id'), 'archived_overall_reconciliations', ['id'], unique=False)
    op.create_index(op.f('ix_archived_overall_reconciliations_session_id'), 'archived_overall_reconciliations', ['session_id'], unique=False)
    op.create_table('archived_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('closing_balance', sa.Float(), nullable=True),
    sa.Column('original_created_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_reconciliations_client_id'), 'archived_reconciliations', ['client_id'], unique=False)
    op.create_index(op.f('ix_archived_reconciliations_financial_year_id'), 'archived_reconciliations', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_archived_reconciliations_id'), 'archived_reconciliations', ['id'], unique=False)
    op.create_index(op.f('ix_archived_reconciliations_month'), 'archived_reconciliations', ['month'], unique=False)
    op.create_index(op.f('ix_archived_reconciliations_session_id'), 'archived_reconciliations', ['session_id'], unique=False)
    op.create_table('archived_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('locked', sa.Integer(), nullable=True),
    sa.Column('friendly_name', sa.String(), nullable=True),
    sa.Column('original_created_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_sessions_client_id'), 'archived_sessions', ['client_id'], unique=False)
    op.create_index(op.f('ix_archived_sessions_financial_year_id'), 'archived_sessions', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_archived_sessions_id'), 'archived_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_archived_sessions_session_id'), 'archived_sessions', ['session_id'], unique=False)
    op.create_table('archived_transaction_merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('original_transaction_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('original_created_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_transaction_merchants_financial_year_id'), 'archived_transaction_merchants', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_archived_transaction_merchants_id'), 'archived_transaction_merchants', ['id'], unique=False)
    op.create_index(op.f('ix_archived_transaction_merchants_session_id'), 'archived_transaction_merchants', ['session_id'], unique=False)
    op.create_table('archived_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('original_invoice_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('amount_excl_vat', sa.Float(), nullable=True),
    sa.Column('amount_incl_vat', sa.Float(), nullable=True),
    sa.Column('bank_source', sa.String(), nullable=True),
    sa.Column('balance_verified', sa.Integer(), nullable=True),
    sa.Column('balance_difference', sa.Float(), nullable=True),
    sa.Column('validation_message', sa.String(), nullable=True),
    sa.Column('original_created_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_transactions_client_id'), 'archived_transactions', ['client_id'], unique=False)
    op.create_index(op.f('ix_archived_transactions_financial_year_id'), 'archived_transactions', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_archived_transactions_id'), 'archived_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_archived_transactions_session_id'), 'archived_transactions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archived_transactions_session_id'), table_name='archived_transactions')
    op.drop_index(op.f('ix_archived_transactions_id'), table_name='archived_transactions')
    op.drop_index(op.f('ix_archived_transactions_financial_year_id'), table_name='archived_transactions')
    op.drop_index(op.f('ix_archived_transactions_client_id'), table_name='archived_transactions')
    op.drop_table('archived_transactions')
    op.drop_index(op.f('ix_archived_transaction_merchants_session_id'), table_name='archived_transaction_merchants')
    op.drop_index(op.f('ix_archived_transaction_merchants_id'), table_name='archived_transaction_merchants')
    op.drop_index(op.f('ix_archived_transaction_merchants_financial_year_id'), table_name='archived_transaction_merchants')
    op.drop_table('archived_transaction_merchants')
    op.drop_index(op.f('ix_archived_sessions_session_id'), table_name='archived_sessions')
    op.drop_index(op.f('ix_archived_sessions_id'), table_name='archived_sessions')
    op.drop_index(op.f('ix_archived_sessions_financial_year_id'), table_name='archived_sessions')
    op.drop_index(op.f('ix_archived_sessions_client_id'), table_name='archived_sessions')
    op.drop_table('archived_sessions')
    op.drop_index(op.f('ix_archived_reconciliations_session_id'), table_name='archived_reconciliations')
    op.drop_index(op.f('ix_archived_reconciliations_month'), table_name='archived_reconciliations')
    op.drop_index(op.f('ix_archived_reconciliations_id'), table_name='archived_reconciliations')
    op.drop_index(op.f('ix_archived_reconciliations_financial_year_id'), table_name='archived_reconciliations')
    op.drop_index(op.f('ix_archived_reconciliations_client_id'), table_name='archived_reconciliations')
    op.drop_table('archived_reconciliations')
    op.drop_index(op.f('ix_archived_overall_reconciliations_session_id'), table_name='archived_overall_reconciliations')
    op.drop_index(op.f('ix_archived_overall_reconciliations_id'), table_name='archived_overall_reconciliations')
    op.drop_index(op.f('ix_archived_overall_reconciliations_financial_year_id'), table_name='archived_overall_reconciliations')
    op.drop_index(op.f('ix_archived_overall_reconciliations_client_id'), table_name='archived_overall_reconciliations')
    op.drop_table('archived_overall_reconciliations')
    op.drop_index(op.f('ix_archived_invoices_session_id'), table_name='archived_invoices')
    op.drop_index(op.f('ix_archived_invoices_id'), table_name='archived_invoices')
    op.drop_index(op.f('ix_archived_invoices_financial_year_id'), table_name='archived_invoices')
    op.drop_index(op.f('ix_archived_invoices_client_id'), table_name='archived_invoices')
    op.drop_table('archived_invoices')
    op.drop_index(op.f('ix_archived_invoice_matches_id'), table_name='archived_invoice_matches')
    op.drop_index(op.f('ix_archived_invoice_matches_financial_year_id'), table_name='archived_invoice_matches')
    op.drop_table('archived_invoice_matches')
    op.drop_index(op.f('ix_financial_years_id'), table_name='financial_years')
    op.drop_index(op.f('ix_financial_years_client_id'), table_name='financial_years')
    op.drop_table('financial_years')
    op.drop_index(op.f('ix_backup_records_user_id'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_id'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_created_at'), table_name='backup_records')
    op.drop_table('backup_records')
    # ### end Alembic commands ###
