"""Initial migration with all tables

Revision ID: a9d0008eea5f
Revises: 
Create Date: 2026-02-12 14:07:03.735016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d0008eea5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False)
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('custom_categories', 'vat_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(15.0)'))
    op.drop_index('idx_overall_reconciliations_client_id', table_name='overall_reconciliations')
    op.drop_index('ix_overall_reconciliations_session_id', table_name='overall_reconciliations')
    op.create_index(op.f('ix_overall_reconciliations_session_id'), 'overall_reconciliations', ['session_id'], unique=False)
    op.create_index(op.f('ix_overall_reconciliations_client_id'), 'overall_reconciliations', ['client_id'], unique=False)
    op.create_foreign_key(None, 'overall_reconciliations', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_reconciliations_client_id', table_name='reconciliations')
    op.create_index(op.f('ix_reconciliations_client_id'), 'reconciliations', ['client_id'], unique=False)
    op.create_foreign_key(None, 'reconciliations', 'clients', ['client_id'], ['id'])
    op.alter_column('transactions', 'vat_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('transactions', 'amount_excl_vat',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('transactions', 'amount_incl_vat',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('transactions', 'balance_difference',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('transactions', 'validation_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'validation_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('transactions', 'balance_difference',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('transactions', 'amount_incl_vat',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('transactions', 'amount_excl_vat',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('transactions', 'vat_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'reconciliations', type_='foreignkey')
    op.drop_index(op.f('ix_reconciliations_client_id'), table_name='reconciliations')
    op.create_index('idx_reconciliations_client_id', 'reconciliations', ['client_id'], unique=False)
    op.drop_constraint(None, 'overall_reconciliations', type_='foreignkey')
    op.drop_index(op.f('ix_overall_reconciliations_client_id'), table_name='overall_reconciliations')
    op.drop_index(op.f('ix_overall_reconciliations_session_id'), table_name='overall_reconciliations')
    op.create_index('ix_overall_reconciliations_session_id', 'overall_reconciliations', ['session_id'], unique=1)
    op.create_index('idx_overall_reconciliations_client_id', 'overall_reconciliations', ['client_id'], unique=False)
    op.alter_column('custom_categories', 'vat_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(15.0)'))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.alter_column('clients', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
